/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package cartese.view;

import cartese.domain.ShoppingCartEseDomain;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

import com.akkaserverless.javasdk.view.ViewContext;

public class OrdersByCustomerEseViewImplView extends AbstractOrdersByCustomerEseViewImplView {

  public OrdersByCustomerEseViewImplView(ViewContext context) {
  }

  @Override
  public ShoppingCartEseDomain.Cart emptyState() {
    return ShoppingCartEseDomain.Cart.newBuilder().build();
  }

  @Override
  public UpdateEffect<ShoppingCartEseDomain.Cart> updateItemAdded(ShoppingCartEseDomain.Cart state, ShoppingCartEseDomain.ItemAdded event) {
    var shoppingCart = ShoppingCart.toShoppingCart(state);
    shoppingCart.handle(event);
    return effects().updateState(shoppingCart.toDomain());
  }

  @Override
  public UpdateEffect<ShoppingCartEseDomain.Cart> updateItemChangedQuantity(ShoppingCartEseDomain.Cart state, ShoppingCartEseDomain.ItemChangedQuantity event) {
    var shoppingCart = ShoppingCart.toShoppingCart(state);
    shoppingCart.handle(event);
    return effects().updateState(shoppingCart.toDomain());
  }

  @Override
  public UpdateEffect<ShoppingCartEseDomain.Cart> updateItemRemoved(ShoppingCartEseDomain.Cart state, ShoppingCartEseDomain.ItemRemoved event) {
    var shoppingCart = ShoppingCart.toShoppingCart(state);
    shoppingCart.handle(event);
    return effects().updateState(shoppingCart.toDomain());
  }

  @Override
  public UpdateEffect<ShoppingCartEseDomain.Cart> updateCheckedOut(ShoppingCartEseDomain.Cart state, ShoppingCartEseDomain.CheckedOut event) {
    var shoppingCart = ShoppingCart.toShoppingCart(state);
    shoppingCart.handle(event);
    return effects().updateState(shoppingCart.toDomain());
  }

  @Override
  public UpdateEffect<ShoppingCartEseDomain.Cart> updateCartRemoved(ShoppingCartEseDomain.Cart state, ShoppingCartEseDomain.CartRemoved event) {
    var shoppingCart = ShoppingCart.toShoppingCart(state);
    shoppingCart.handle(event);
    return effects().updateState(shoppingCart.toDomain());
  }

  static class ShoppingCart {
    String customerId;
    String cartId;
    boolean checkedOut;
    boolean deleted;
    Map<String, LineItem> items = new LinkedHashMap<>();

    static class LineItem {
      String productId;
      String name;
      int quantity;

      LineItem(String productId, String name, int quantity) {
        this.productId = productId;
        this.name = name;
        this.quantity = quantity;
      }
    }

    void handle(ShoppingCartEseDomain.ItemAdded event) {
      cartId = event.getCartId();
      customerId = event.getCustomerId();
      items.put(event.getItem().getProductId(), toItem(event.getItem()));
    }

    void handle(ShoppingCartEseDomain.ItemChangedQuantity event) {
      items.computeIfPresent(event.getProductId(), ((key, value) -> new LineItem(key, value.name, event.getQuantity())));
    }

    void handle(ShoppingCartEseDomain.ItemRemoved event) {
      items.remove(event.getProductId());
    }

    void handle(ShoppingCartEseDomain.CheckedOut event) {
      checkedOut = true;
    }

    void handle(ShoppingCartEseDomain.CartRemoved event) {
      deleted = true;
    }

    static ShoppingCart toShoppingCart(Optional<ShoppingCartEseDomain.Cart> state) {
      return toShoppingCart(state.orElse(ShoppingCartEseDomain.Cart.newBuilder().build()));
    }

    static ShoppingCart toShoppingCart(ShoppingCartEseDomain.Cart domain) {
      var cart = new ShoppingCart();
      cart.cartId = domain.getCartId();
      cart.customerId = domain.getCustomerId();
      cart.checkedOut = domain.getCheckedOut();
      cart.deleted = domain.getDeleted();
      domain.getItemsList().forEach(item -> cart.items.put(item.getProductId(), toItem(item)));
      return cart;
    }

    private static LineItem toItem(ShoppingCartEseDomain.LineItem item) {
      return new LineItem(item.getProductId(), item.getName(), item.getQuantity());
    }

    ShoppingCartEseDomain.Cart toDomain() {
      return ShoppingCartEseDomain.Cart
          .newBuilder()
          .setCartId(cartId)
          .setCustomerId(customerId)
          .setCheckedOut(checkedOut)
          .setDeleted(deleted)
          .addAllItems(items.values().stream().map(item -> toDomainLineItem(item)).collect(Collectors.toList()))
          .build();
    }

    private ShoppingCartEseDomain.LineItem toDomainLineItem(LineItem item) {
      return ShoppingCartEseDomain.LineItem
          .newBuilder()
          .setProductId(item.productId)
          .setName(item.name)
          .setQuantity(item.quantity)
          .build();
    }
  }
}