
### For use with VSCode Rest Client extension

# @urlPrefix = http://localhost:9000

@urlPrefix = https://black-dream-3128.us-east1.akkaserverless.app
@customerId = customer-1
@cartId = cart-1
@productId = product-1
@productName = product name 1
@quantity = 1

### cartve.CartService.AddItem

curl -XPOST -H "Content-Type: application/json" -d '{
  "customer_id": "{{customerId}}",
  "product_id": "{{productId}}",
  "name": "{{productName}}",
  "quantity": {{quantity}}
}' {{urlPrefix}}/ve/cart/{{cartId}}/items/add

### cartve.CartService.ChangeItem

curl -XPUT -H "Content-Type: application/json" -d '{
  "quantity": {{quantity}}
}' {{urlPrefix}}/ve/cart/{{cartId}}/items/{{productId}}/change

### cartve.CartService.CheckoutCart

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ve/cart/{{cartId}}/checkout

### cartve.CartService.GetCart

curl -XGET -H "Content-Type: application/json" {{urlPrefix}}/ve/carts/{{cartId}}

### cartve.CartService.RemoveCart

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ve/carts/{{cartId}}/remove

### cartve.CartService.RemoveItem

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ve/cart/{{cartId}}/items/{{productId}}/remove

### cartve.view.OrdersByCustomerEseView.GetOrdersByCustomer

curl -XGET -H "Content-Type: application/json" "{{urlPrefix}}/ve/orders?customer_id={{customerId}}"
