
### For use with VSCode Rest Client extension

# @urlPrefix = http://localhost:9000
@urlPrefix = https://black-dream-3128.us-east1.akkaserverless.app
@customerId = customer-1
@cartId = cart-1
@productId = product-1
@productName = product name 1
@quantity = 1

### cartese.CartService.AddItem

curl -XPOST -H "Content-Type: application/json" -d '{
  "customer_id": "{{customerId}}",
  "product_id": "{{productId}}",
  "name": "{{productName}}",
  "quantity": {{quantity}}
}' {{urlPrefix}}/ese/cart/{{cartId}}/items/add

### cartese.CartService.ChangeItem

curl -XPUT -H "Content-Type: application/json" -d '{
  "quantity": {{quantity}}
}' {{urlPrefix}}/ese/cart/{{cartId}}/items/{{productId}}/change

### cartese.CartService.CheckoutCart

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/cart/{{cartId}}/checkout

### cartese.CartService.GetCart

curl -XGET -H "Content-Type: application/json" {{urlPrefix}}/ese/carts/{{cartId}}

### cartese.CartService.RemoveCart

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/carts/{{cartId}}/remove

### cartese.CartService.RemoveItem

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/cart/{{cartId}}/items/{{productId}}/remove

### cartese.view.OrdersByCustomerEseView.GetOrdersByCustomer

curl -XGET -H "Content-Type: application/json" "{{urlPrefix}}/ese/orders?customer_id={{customerId}}"
