/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package cartese.action.in;

import com.akkaserverless.javasdk.action.ActionCreationContext;
import com.google.protobuf.Empty;

/** An action. */
public class ShoppingCartEseTopicInAction extends AbstractShoppingCartEseTopicInAction {

  public ShoppingCartEseTopicInAction(ActionCreationContext creationContext) {}

  /** Handler for "AddItem". */
  @Override
  public Effect<Empty> addItem(ShoppingCartEseActionTopicIn.AddLineItem addLineItem) {
    throw new RuntimeException("The command handler for `AddItem` is not implemented, yet");
  }
  /** Handler for "ChangeItem". */
  @Override
  public Effect<Empty> changeItem(ShoppingCartEseActionTopicIn.ChangeLineItemQuantity changeLineItemQuantity) {
    throw new RuntimeException("The command handler for `ChangeItem` is not implemented, yet");
  }
  /** Handler for "RemoveItem". */
  @Override
  public Effect<Empty> removeItem(ShoppingCartEseActionTopicIn.RemoveLineItem removeLineItem) {
    throw new RuntimeException("The command handler for `RemoveItem` is not implemented, yet");
  }
  /** Handler for "CheckoutCart". */
  @Override
  public Effect<Empty> checkoutCart(ShoppingCartEseActionTopicIn.CheckoutShoppingCart checkoutShoppingCart) {
    throw new RuntimeException("The command handler for `CheckoutCart` is not implemented, yet");
  }
  /** Handler for "RemoveCart". */
  @Override
  public Effect<Empty> removeCart(ShoppingCartEseActionTopicIn.RemoveShoppingCart removeShoppingCart) {
    throw new RuntimeException("The command handler for `RemoveCart` is not implemented, yet");
  }
}