/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package cartve.action;

import com.akkaserverless.javasdk.action.ActionCreationContext;
import com.google.protobuf.Empty;

public class ShoppingCartVeToTopicAction extends AbstractShoppingCartVeToTopicAction {

  public ShoppingCartVeToTopicAction(ActionCreationContext creationContext) {
  }

  @Override
  public Effect<Empty> addItem(ShoppingCartVeToTopicOuter.AddLineItem addLineItem) {
    throw new RuntimeException("The command handler for `AddItem` is not implemented, yet");
  }

  @Override
  public Effect<Empty> changeItem(ShoppingCartVeToTopicOuter.ChangeLineItemQuantity changeLineItemQuantity) {
    throw new RuntimeException("The command handler for `ChangeItem` is not implemented, yet");
  }

  @Override
  public Effect<Empty> removeItem(ShoppingCartVeToTopicOuter.RemoveLineItem removeLineItem) {
    throw new RuntimeException("The command handler for `RemoveItem` is not implemented, yet");
  }

  @Override
  public Effect<Empty> checkoutCart(ShoppingCartVeToTopicOuter.CheckoutShoppingCart checkoutShoppingCart) {
    throw new RuntimeException("The command handler for `CheckoutCart` is not implemented, yet");
  }

  @Override
  public Effect<Empty> removeCart(ShoppingCartVeToTopicOuter.RemoveShoppingCart removeShoppingCart) {
    throw new RuntimeException("The command handler for `RemoveCart` is not implemented, yet");
  }
}