/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package cartve.view;

import cartve.entity.ShoppingCartVeEntity;
import com.akkaserverless.javasdk.view.ViewContext;

public class OrdersByCustomerVeViewImpl extends AbstractOrdersByCustomerVeView {

  public OrdersByCustomerVeViewImpl(ViewContext context) {}

  
}
